spring:
  application:
    name: iam-service

  security:
    jwt:
      secret-key: 1Zc9csmGVH+oWdEIqmFgAAlq4ssArFnilYPbUApNr7TxlIXz4nkHUSJjL8+sIYYB
      expiration-time: 86400000 # 24 hours

  datasource:

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

swagger:
  host-url: http://localhost:8080

app:
  default-admin:
    password: admin123
