spring:
  application:
    name: iam-service

  security:
    jwt:
      secret-key: mySecretKey12345678901234567890123456789012345678901234567890
      expiration-time: 86400000 # 24 hours

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

swagger:
  host-url: http://localhost:8080
